### ISSUE TITLE
Add a way to "solo" a layer

### ISSUE THREAD

**Issue by kasbah** [tracespace/viewer#13]
It would be great to be able to have a way to only make one layer visible and hide the rest and then have a quick way to show all the layers again. A bit like a "solo" button on a music sequencer. 

Intuitively I expected this to happen on a double click of the eye icon (not sure why), but doing it that way may not be so obvious to others and lack discover-ability. It would probably be best to add another button.

**Comment by mcous** [comment]
This makes a lot of sense. You're right about the mechanism; it need to be intuitive. Another button is easy. Any idea which one would make the most sense? http://fontawesome.io/icons/

I'm reminded of a thing you can do in some 3D CAD programs (e.g Pro/E), where in an assembly you could select a single part and "highlight" it by making all other parts go mostly transparent. I'd like to play around with both hiding all other layers and de-emphasizing all other layers and see what they're both like.

**Comment by mcous** [comment]
Just gonna dump these here:

http://fontawesome.io/icon/binoculars/
http://fontawesome.io/icon/crosshairs/
http://fontawesome.io/icon/lightbulb-o/
http://fontawesome.io/icon/low-vision/

**Comment by kasbah** [comment]
Out of those ones, probably the crosshairs. Using a button with just an `s` in the middle would carry over the convention from music software. I have never seen this kind of action in CAD software so I don't think there is any other convention.

Similar to the crosshairs is http://fontawesome.io/icon/bullseye/. 

Some other maybes:
Indent: http://fontawesome.io/icon/indent/
Hand: http://fontawesome.io/icon/hand-o-left/
Chevron: http://fontawesome.io/icon/chevron-circle-left/

**Comment by kasbah** [comment]
![](https://store-images.s-microsoft.com/image/apps.2744.9007199266297043.ede8fc69-94ea-410e-a25f-69116139f8af.7a07216e-aeb9-4fc2-be78-ddcbd97dd112?w=96&h=96&q=60)
