### ISSUE TITLE
Re-deploy with whats-that-gerber 2.1.0 for OSHpark-Eagle filenames?

### ISSUE THREAD

**Issue by kasbah** [tracespace/viewer#14]
Would be good to have the OSHpark Eagle filename detection on viewer.

**Comment by mcous** [comment]
Ugh yeah, keep telling myself "Oh, I'll grab these deps when I deploy for new feature 'x'", and then 'x' takes longer than I expected.

Kicking of a build now because I can't be trusted with time management...

**Comment by mcous** [comment]
Deployed!
