### ISSUE TITLE
Empty bottom copper messes up board view

### ISSUE THREAD

**Issue by kasbah** [tracespace/viewer#15]
With the bottom copper (which is actually empty) the board view shows only the outline on these. If you delete the bottom copper layer it will show the top mask and coppers as expected. Added as a pcb-stackup integration test, even with the empty layer, this board renders fine. 

[jelly.zip](https://github.com/tracespace/viewer/files/440305/jelly.zip)

**Comment by mcous** [comment]
No idea why this is happening! Probably something to do with the way individual layers are shared between the stackup view and the layers view. It's been a busy week, so hopefully I'll have time to look at it this weekend
