### ISSUE TITLE
support zip file

### ISSUE THREAD

**Issue by 3lang3** [tracespace/viewer#17]
Consider supporting ZIP files?
Otherwise we need to upload many times

btw， the project is cool
cool

**Comment by 3lang3** [comment]
#12

**Comment by mcous** [comment]
Hi @EthanOrange, I'm glad you like the project! I would love to add zip support as mentioned in #12 but I just haven't had time to work on this project.

In the mean time, you can select multiple files during one upload by holding ctrl (or cmd on macOS) or shift when selecting files.
